# Generated by Django 5.1.1 on 2024-09-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
