# Generated by Django 5.1.1 on 2024-09-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botik', '0003_companies_customers_orders_partners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Companie',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
    ]
