# Generated by Django 5.1.1 on 2024-09-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botik', '0004_rename_companies_companie_rename_customers_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='login',
            new_name='email',
        ),
    ]
