# Generated by Django 5.1.1 on 2024-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botik', '0005_rename_login_partner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
