# Generated by Django 5.1.1 on 2024-09-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botik', '0008_remove_order_id_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='role',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
