# Generated by Django 5.1.1 on 2024-09-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botik', '0009_partner_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
