# Generated by Django 5.1.1 on 2024-09-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botik', '0010_customer_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
