# Generated by Django 5.1.1 on 2024-09-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botik', '0011_customer_orders_count_alter_customer_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders_count',
            field=models.BigIntegerField(default=-1),
        ),
    ]
