# Generated by Django 5.1.1 on 2024-09-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botik', '0012_alter_customer_orders_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_details',
            field=models.CharField(max_length=250),
        ),
    ]
