# Generated by Django 5.1.1 on 2024-09-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botik', '0013_order_status_alter_order_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tg_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
